// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_api.Datos;

#nullable disable

namespace proyecto_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231227212634_AlimentarTablaProyecto")]
    partial class AlimentarTablaProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyecto_api.Modelos.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Puntuacion")
                        .HasColumnType("float");

                    b.Property<bool>("Terminado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Mimosa Misas",
                            Descripcion = "Ninguna...",
                            FechaPublicacion = new DateTime(2023, 12, 27, 16, 26, 34, 450, DateTimeKind.Local).AddTicks(6482),
                            Nombre = "La niña del aro",
                            Puntuacion = 2.0,
                            Terminado = false
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Juan Misas",
                            Descripcion = "pelicula fenizi...",
                            FechaPublicacion = new DateTime(2023, 12, 27, 16, 26, 34, 450, DateTimeKind.Local).AddTicks(6494),
                            Nombre = "Barbie",
                            Puntuacion = 2.0,
                            Terminado = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
